--{} NORMAL_TYPE
--@pk:OID
--{} init

--{} update
--{} 2019,08,12
update CO_XSL_GIFT GIFT_NAME = '1000吋行李箱(閃耀銀)(291)' where GIFT_ID = '291';
-- -- INSERT INTO CO_XSL_GIFT (OID, GIFT_ID, GIFT_NAME, PIC_URL, ACTION_FLAG, MODIFY_DATE, MODIFIER, EXPORT_NO, DESC_HTML, EDM_DESC, CFMPG_PIC_URL, THX_BENEFIT_DESC) VALUES ('KFIKSISUJDIJD9JKDUPMPLDOE', '290', '韓國Neoflam鈦金不沾鍋具4件組(290)', '', 'A', current_timestamp, 'user001', null, '<p>NO_NEED_TO_USE</p>', '', 'NO_NEED_TO_USE', null);
-- INSERT INTO CO_XSL_GIFT (OID, GIFT_ID, GIFT_NAME, PIC_URL, ACTION_FLAG, MODIFY_DATE, MODIFIER, EXPORT_NO, DESC_HTML, EDM_DESC, CFMPG_PIC_URL, THX_BENEFIT_DESC) VALUES ('KFIKSISUJDIJD9JKDUPIKDIWH', '291', '29吋行李箱(閃耀銀)(291)', '', 'A', current_timestamp, 'user001', null, '<p>NO_NEED_TO_USE</p>', '', 'NO_NEED_TO_USE', null);
-- INSERT INTO CO_XSL_GIFT (OID, GIFT_ID, GIFT_NAME, PIC_URL, ACTION_FLAG, MODIFY_DATE, MODIFIER, EXPORT_NO, DESC_HTML, EDM_DESC, CFMPG_PIC_URL, THX_BENEFIT_DESC) VALUES ('KFIKSISUJDIJD9JKDUPMFKSOW', '292', '29吋行李箱(閃耀藍)(292)', '', 'A', current_timestamp, 'user001', null, '<p>NO_NEED_TO_USE</p>', '', 'NO_NEED_TO_USE', null);
-- INSERT INTO CO_XSL_GIFT (OID, GIFT_ID, GIFT_NAME, PIC_URL, ACTION_FLAG, MODIFY_DATE, MODIFIER, EXPORT_NO, DESC_HTML, EDM_DESC, CFMPG_PIC_URL, THX_BENEFIT_DESC) VALUES ('KFIKSISUJDIJD9JKDUPPDDIDD', '293', '懶骨頭沙發(293)', '', 'A', current_timestamp, 'user001', null, '<p>NO_NEED_TO_USE</p>', '', 'NO_NEED_TO_USE', null);





