--EMGM_CFG_SYSPARM.sql
--{} 2018,11,09
UPDATE [dbo].EMGM_CFG_SYSPARM SET parmValue = 'NO'
WHERE parmId = 'DEVELOP_TEST';
--UPDATE [dbo].EMGM_CFG_SYSPARM SET parmValue = 'NO'
--WHERE parmId = 'DEVELOP_OTP_TEST';

--EMGM_SHARE_LINK_COUNT.sql

--EMGM_LOCKEDINFO.sql

--EMGM_API_TRANSLOG.sql

--EMGM_REFERRER_INFO.sql

